name: Deploy Frontend (Afspraakplanner)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies & build
        run: |
          cd frontend
          npm install
          npm run build

      - name: Copy web.config to build output
        run: cp frontend/web.config frontend/dist/web.config

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: afspraakplanner-frontend
          slot-name: production
          package: frontend/dist